# What's the language of the ASR model (if any, is optional)
# the language, if set, will be appended to the publishing topic like this:
# /whisperasr/asrresult/<lang>

language: en

monitor_mic: false
monitor_asr: false

# host of MQTT broker (specify port, too, if necessary)
mqtt:
  host: host.docker.internal # running in isolated docker

# sample rate of the ASR model (currently 16k)
asr_sample_rate: 16000

whisper:
  model_size: medium
  device: gpu
  compute_type: float32

vad:
  threshold: 0.2
  min_silence_duration_ms: 300

whisper_transcription:
  language: en
  vad_filter: false
